### ISSUE TITLE
Support of categorical variables

### ISSUE THREAD

**Issue by jpaciello** [jpmml/jpmml-h2o#13]
My model is a H2O Gradient Boosting Machine Learner trained using the Knime IDE with the H2O Machine Learning extension. I save it to a MOJO file and then use your project following all the steps. The model uses categorical and numerical variables, the categorical are in String format and I use the Domain Calculator of Knime to treat them as categorical.

I'm getting this error stack:
```
Exception in thread "main" java.lang.IllegalArgumentException: Field nivel_1 has data type string
        at org.jpmml.converter.PMMLEncoder.toContinuous(PMMLEncoder.java:209)
        at org.jpmml.converter.CategoricalFeature.toContinuousFeature(CategoricalFeature.java:56)
        at org.jpmml.h2o.SharedTreeMojoModelConverter.encodeNode(SharedTreeMojoModelConverter.java:195)
        at org.jpmml.h2o.SharedTreeMojoModelConverter.encodeNode(SharedTreeMojoModelConverter.java:257)
        at org.jpmml.h2o.SharedTreeMojoModelConverter.encodeNode(SharedTreeMojoModelConverter.java:221)
        at org.jpmml.h2o.SharedTreeMojoModelConverter.encodeNode(SharedTreeMojoModelConverter.java:257)
        at org.jpmml.h2o.SharedTreeMojoModelConverter.encodeNode(SharedTreeMojoModelConverter.java:221)
        at org.jpmml.h2o.SharedTreeMojoModelConverter.encodeNode(SharedTreeMojoModelConverter.java:257)
        at org.jpmml.h2o.SharedTreeMojoModelConverter.encodeNode(SharedTreeMojoModelConverter.java:221)
        at org.jpmml.h2o.SharedTreeMojoModelConverter.encodeNode(SharedTreeMojoModelConverter.java:221)
        at org.jpmml.h2o.SharedTreeMojoModelConverter.encodeNode(SharedTreeMojoModelConverter.java:221)
        at org.jpmml.h2o.SharedTreeMojoModelConverter.encodeNode(SharedTreeMojoModelConverter.java:221)
        at org.jpmml.h2o.SharedTreeMojoModelConverter.encodeTreeModel(SharedTreeMojoModelConverter.java:98)
        at org.jpmml.h2o.SharedTreeMojoModelConverter.lambda$encodeTreeModels$0(SharedTreeMojoModelConverter.java:74)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.jpmml.h2o.SharedTreeMojoModelConverter.encodeTreeModels(SharedTreeMojoModelConverter.java:75)
        at org.jpmml.h2o.GbmMojoModelConverter.encodeModel(GbmMojoModelConverter.java:58)
        at org.jpmml.h2o.Converter.encodePMML(Converter.java:87)
        at org.jpmml.h2o.example.Main.run(Main.java:123)
        at org.jpmml.h2o.example.Main.main(Main.java:93)
```
Your project works with categorical variables stored as Strings? If not, what should be the type for categorical variables?

Thanks in advance!
Julio Paciello
from Paraguay

**Comment by vruusmann** [comment]
This is a failing sanity check, which signals that your data schema and your model object are out-of-sync. Specifically, your data schema provides a categorical variable, but the model object expects a continuous variable instead.

The H2O node type is detected as "continuous" using this code path:
https://github.com/jpmml/jpmml-h2o/blob/1.2.5/pmml-h2o/src/main/java/org/jpmml/h2o/SharedTreeMojoModelConverter.java#L115

The value of the `equal` local variable must be `0` ("continuous split"), because the code ends up here (this is where the exception is thrown):
https://github.com/jpmml/jpmml-h2o/blob/1.2.5/pmml-h2o/src/main/java/org/jpmml/h2o/SharedTreeMojoModelConverter.java#L195

> the categorical are in String format and I use the Domain Calculator of Knime to treat them as categorical.

This Domain Calculator conversion lives in KNIME environment, it is not stored in H2O MOJO file.

> Your project works with categorical variables stored as Strings?

AFAIK, the H2O framework only supports categorical strings. The (J)PMML framework supports complex type definitions, where the categorical operational type can be combined with any data type (string, numeric, boolean, date/time/datetime etc).

>  If not, what should be the type for categorical variables?

In the current case, you may need to develop a custom piece of Java code that prepares an `org.jpmml.converter.Schema` object that mirrors the data schema as exists within the KNIME environment (after all Domain Calculators have been applied).

**Comment by vruusmann** [comment]
Closing as "data schema mis-communication between KNIME and H2O frameworks". This can't be addressed at the JPMML-H2O library level.
