### ISSUE TITLE
Throws error when I change the max_depth > 5 and ntrees = 100  for a GBM

### ISSUE THREAD

**Issue by michaelsoliman-com** [jpmml/jpmml-h2o#2]
When I change the max_depth for a GBM model in H2O, export the mojo, and try to convert it with the tool, it throws the following error:
```
Exception in thread "main" java.lang.IllegalArgumentException
        at org.jpmml.h2o.SharedTreeMojoModelConverter.encodeNode(SharedTreeMojoModelConverter.java:87)
        at org.jpmml.h2o.SharedTreeMojoModelConverter.encodeTreeModel(SharedTreeMojoModelConverter.java:68)
        at org.jpmml.h2o.GbmMojoModelConverter.lambda$encodeModel$0(GbmMojoModelConverter.java:73)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.jpmml.h2o.GbmMojoModelConverter.encodeModel(GbmMojoModelConverter.java:74)
        at org.jpmml.h2o.GbmMojoModelConverter.encodeModel(GbmMojoModelConverter.java:48)
        at org.jpmml.h2o.Converter.encodePMML(Converter.java:71)
        at org.jpmml.h2o.Main.run(Main.java:107)
        at org.jpmml.h2o.Main.main(Main.java:88)
```

The error happens for when I change the max_depth for any value above 5 with ntrees = 100

![image](https://user-images.githubusercontent.com/13219845/45361203-a35cde00-b59f-11e8-860b-28e954cc7dc1.png)

H2O version 3.19.0.4274

**Comment by vruusmann** [comment]
Here's the offending sanity check:
https://github.com/jpmml/jpmml-h2o/blob/master/src/main/java/org/jpmml/h2o/SharedTreeMojoModelConverter.java#L85-L88

Looks like H2O uses a different encoding mechanism for small (max_depth <=5) and large (max_depth > 5) decision tree objects. My integration tests only cover small trees (for performance reasons); looks like I should upgrade them to include some large trees as well.

**Comment by vruusmann** [comment]
Increased the number of trees to 131, and set max depth to 8 in the following two places:
https://github.com/jpmml/jpmml-h2o/blob/master/src/test/resources/main.py#L47
https://github.com/jpmml/jpmml-h2o/blob/master/src/test/resources/main.py#L49

Everything works perfectly.

My conclusion is that the `max_depth` alone is not causing this issue, there must be something else "assisting" it. Need a reproducible example in order to start fixing this.

**Comment by vruusmann** [comment]
Haven't observed anything like this in the 2018 -- 2023 time period.
